main: io.github.pokeba.CrashPreventer.CrashPreventerMain
name: CrashPreventer
version: 1.0
author: Poke
description: Prevent crash from modded items being put where they should not be.
commands:
 crashpreventer:
  description: Prevents player from putting blacklisted item in blacklisted block
  permission: bopcrashfix.basic
  permission-message: You don't have the permissions to do that!